apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: go-executor-operator-system
spec:
  containers:
  - name: busybox-container
    image: busybox
    command:
    - sleep
    - "3600"  # Sleep for 1 hour, you can adjust the sleep duration as needed
  restartPolicy: Never

