# permissions for end users to edit executors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: executor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-executor-operator
    app.kubernetes.io/part-of: go-executor-operator
    app.kubernetes.io/managed-by: kustomize
  name: executor-editor-role
rules:
- apiGroups:
  - executor.invoker.io
  resources:
  - executors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - executor.invoker.io
  resources:
  - executors/status
  verbs:
  - get
