# permissions for end users to view invokerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: invokerdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: invoker-operator
    app.kubernetes.io/part-of: invoker-operator
    app.kubernetes.io/managed-by: kustomize
  name: invokerdeployment-viewer-role
rules:
- apiGroups:
  - invokeroperator.invoker.io
  resources:
  - invokerdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - invokeroperator.invoker.io
  resources:
  - invokerdeployments/status
  verbs:
  - get
