apiVersion: executor.invoker.io/v1alpha1
kind: Executor
metadata:
  labels:
    app.kubernetes.io/name: executor
    app.kubernetes.io/instance: executor-sample
    app.kubernetes.io/part-of: go-executor-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: go-executor-operator
  name: executor-sample
  namespace: default
spec:
  imagePullPolicy: "IfNotPresent"
  statefulEntities:
    - brokerIp: "host.docker.internal:9092"
      image: "executor-word-count:testv1"
      inputSidecar: "iosidecar:testv1"
      inputTopic: "test"
      stateSidecar: "statesidecar:testv1"
      outputSidecar: "producersidecar:testv1"
      outputTopic: "count"
      name: "word-count"
      topology:
       - partitions:
          - "0"
       - partitions:
          - "1"
    - brokerIp: "host.docker.internal:9092"
      image: "executor-sum:testv1"
      inputSidecar: "iosidecar:testv1"
      inputTopic: "count"
      stateSidecar: "statesidecar:testv1"
      outputSidecar: "producersidecar:testv1"
      outputTopic: "output"
      name: "sum"
      topology:
       - partitions:
          - "0"
  resource:
    claims:
    - name: cpu
    - name: memory
    limits:
      cpu: 1
      memory: "1Gi"
    requests:
      cpu: 500m
      memory: "512Mi"
  version: "testv1"
  historyLimit: 3
