apiVersion: invokeroperator.invoker.io/v1alpha1
kind: InvokerDeployment
metadata:
  labels:
    app.kubernetes.io/name: invokerdeployment
    app.kubernetes.io/instance: invokerdeployment-sample
    app.kubernetes.io/part-of: invoker-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: invoker-operator
  name: invokerdeployment-sample
spec:
  imagePullPolicy: "IfNotPresent"
  statefulEntities:
    - executorImage: "ruohang/executor-word-count:testv1"
      inputImage: "ruohang/iosidecar:testv1"
      stateImage: "ruohang/statesidecar:testv1"
      outputImage: "ruohang/producersidecar:testv1"
      ioAddress: "10.64.212.148:9092"
      inputTopic: "test"
      outputTopic: "count"
      name: "word-count"
      pods:
       - partitions:
          - "0"
       - partitions:
          - "1"
    - executorImage: "ruohang/executor-sum:testv1"
      inputImage: "ruohang/iosidecar:testv1"
      stateImage: "ruohang/statesidecar:testv1"
      outputImage: "ruohang/producersidecar:testv1"
      ioAddress: "10.64.212.148:9092"
      inputTopic: "count"
      outputTopic: "output"
      name: "sum"
      pods:
       - partitions:
          - "0"
  version: "testv1"
  historyLimit: 3

